version: '3.7'
services:
  nginx:
    image: nginx:1.10
    volumes:
    - ./nginx.conf:/etc/nginx/nginx.conf:ro
    - ./lila/public:/home/lichess/projects/lila/public:ro
    ports:
    - "80:80/tcp"
    - "443:443/tcp"

  redis:
    image: redis:4

  mongodb:
    image: mongo:3.2

  lichess:
    build: ./
    image: lichess:matt-1
    stdin_open: true
    tty: true
    links:
    - redis:redis
    - mongodb:mongodb
