version: '3.8'
services:
  nginx:
    build:
      context: ./
      dockerfile: dockerfiles/Dockerfile.nginx
    image: lichess/nginx:1.0
    depends_on:
    - lichess
    - lichess-ws
    ports:
    - "80:80/tcp"
    - "443:443/tcp"
    volumes:
    - "./nginx.conf:/etc/nginx/nginx.conf:ro"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  redis:
    image: redis:4
    command: ["--loglevel", "verbose"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  mongodb:
    image: mongo:4.2
    environment:
    - MONGO_INITDB_DATABASE=lichess
    volumes:
    - "./mongodb/users.js:/docker-entrypoint-initdb.d/users.js:ro"
    healthcheck:
      test: ["CMD-SHELL", "echo", "'db.runCommand(\"ping\").ok'", "|", "mongo", "localhost:27017/test", "--quiet"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 120s

  influxdb:
    image: influxdb:1.7
    volumes:
    - "./influxdb/init.iql:/docker-entrypoint-initdb.d/init.iql:ro"
    healthcheck:
      test: ["CMD", "curl", "-f", "-XGET", "http://localhost:8086/ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  fishnet:
    image: mklemenz/fishnet
    depends_on:
    - nginx
    - lichess
    links:
    - nginx:www.lichess.local
    command: ["-v", "-v", "-v", "--key", "MYAPIKEY", "--auto-update", "--endpoint", "http://www.lichess.local/fishnet/", "run"]

  lichess:
    build:
      context: ./
      dockerfile: dockerfiles/Dockerfile.lichess
    image: lichess:85690c
    stdin_open: true
    tty: true
    depends_on:
    - redis
    - mongodb
    links:
    - redis:redis
    - mongodb:mongodb
    volumes:
    - ./application.conf:/home/lichess/projects/lila/conf/application.conf:ro
    - ./GeoLite2-City.mmdb:/home/lichess/projects/lila/data/GeoLite2-City.mmdb:ro
    healthcheck:
      test: ["CMD-SHELL", "ss", "-nlt", "|", "grep", "-q", "0.0.0.0:9663"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 120s

  lichess-ws:
    build:
      context: ./
      dockerfile: dockerfiles/Dockerfile.lichess-ws
    image: lichess/ws:245157
    stdin_open: true
    tty: true
    depends_on:
    - redis
    - mongodb
    - influxdb
    links:
    - redis:redis
    - mongodb:mongodb
    - influxdb:influxdb
    ports:
    - "8080/tcp"
    volumes:
    - ./application-ws.conf:/override.conf:ro
    command: ["run", "-Dconfig.file=/override.conf"]
    healthcheck:
      test: ["CMD-SHELL", "ss", "-nlt", "|", "grep", "-q", "0.0.0.0:8080"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 120s
