version: '3.8'
services:
  nginx:
    build:
      context: ./
      dockerfile: dockerfiles/Dockerfile.nginx
    image: lichess/nginx:1.0
    depends_on:
      lichess:
        condition: service_healthy
      lichess-ws:
        condition: service_healthy
    ports:
    - "80:80/tcp"
    - "443:443/tcp"
    volumes:
    - "./nginx.conf:/etc/nginx/nginx.conf:ro"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/"]
      interval: 5s
      timeout: 1s
      retries: 3
      start_period: 5s

  redis:
    image: redis:4
    command: ["--loglevel", "verbose"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 1s
      retries: 3
      start_period: 5s

  mongodb:
    image: mongo:4.2
    environment:
    - MONGO_INITDB_DATABASE=lichess
    volumes:
    - "./mongodb/users.js:/docker-entrypoint-initdb.d/users.js:ro"
    healthcheck:
      test: ["CMD-SHELL", "echo", "'db.runCommand(\"ping\").ok'", "|", "mongo", "localhost:27017/test", "--quiet", "||", "exit", "1"]
      interval: 10s
      timeout: 2s
      retries: 3
      start_period: 10s

  influxdb:
    image: influxdb:1.7
    volumes:
    - "./influxdb/init.iql:/docker-entrypoint-initdb.d/init.iql:ro"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8086/ping"]
      interval: 5s
      timeout: 2s
      retries: 3
      start_period: 10s

#  fishnet:
#    image: mklemenz/fishnet
#    depends_on:
#    - nginx
#    - lichess
#    links:
#    - nginx:www.lichess.local
#    command: ["-v", "-v", "-v", "--key", "MYAPIKEY", "--auto-update", "--endpoint", "http://www.lichess.local/fishnet/", "run"]

  lichess:
    build:
      context: ./
      dockerfile: dockerfiles/Dockerfile.lichess
    image: lichess:85690c
    stdin_open: true
    tty: true
    depends_on:
      redis:
        condition: service_healthy
      mongodb:
        condition: service_healthy
    links:
    - redis:redis
    - mongodb:mongodb
    volumes:
    - ./application.conf:/home/lichess/projects/lila/conf/application.conf:ro
    - ./GeoLite2-City.mmdb:/home/lichess/projects/lila/data/GeoLite2-City.mmdb:ro
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "9663"]
      interval: 5s
      timeout: 2s
      retries: 3
      start_period: 120s

  lichess-ws:
    build:
      context: ./
      dockerfile: dockerfiles/Dockerfile.lichess-ws
    image: lichess/ws:245157
    stdin_open: true
    tty: true
    depends_on:
      redis:
        condition: service_healthy
      mongodb:
        condition: service_healthy
      influxdb:
        condition: service_healthy
      lichess:
        condition: service_healthy
    links:
    - redis:redis
    - mongodb:mongodb
    - influxdb:influxdb
    ports:
    - "8080/tcp"
    volumes:
    - ./application-ws.conf:/override.conf:ro
    command: ["run", "-Dconfig.file=/override.conf"]
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "8080"]
      interval: 5s
      timeout: 2s
      retries: 3
      start_period: 120s
