version: '3.7'
services:
  nginx:
    build:
      context: ./
      dockerfile: dockerfiles/Dockerfile.nginx
    image: lichess/nginx:1.0
    depends_on:
    - lichess
    - lichess-ws
    ports:
    - "80:80/tcp"
    - "443:443/tcp"
    volumes:
    - "./nginx.conf:/etc/nginx/nginx.conf:ro"

  redis:
    image: redis:4
    command: ["--loglevel", "verbose"]

  mongodb:
    image: mongo:4.2
    environment:
    - MONGO_INITDB_DATABASE=lichess
    volumes:
    - "./mongodb/users.js:/docker-entrypoint-initdb.d/users.js:ro"

  influxdb:
    image: influxdb:1.7
    volumes:
    - "./influxdb/init.iql:/docker-entrypoint-initdb.d/init.iql:ro"

  fishnet:
    image: mklemenz/fishnet
    links:
    - nginx:www.lichess.local
    command: ["-v", "-v", "-v", "--key", "MYAPIKEY", "--auto-update", "--endpoint", "http://www.lichess.local/fishnet/", "run"]

  lichess:
    build:
      context: ./
      dockerfile: dockerfiles/Dockerfile.lichess
    image: lichess:85690c
    stdin_open: true
    tty: true
    depends_on:
    - redis
    - mongodb
    links:
    - redis:redis
    - mongodb:mongodb
    volumes:
    - ./application.conf:/home/lichess/projects/lila/conf/application.conf:ro
    - ./GeoLite2-City.mmdb:/home/lichess/projects/lila/data/GeoLite2-City.mmdb:ro

  lichess-ws:
    build:
      context: ./
      dockerfile: dockerfiles/Dockerfile.lichess-ws
    image: lichess/ws:245157
    stdin_open: true
    tty: true
    depends_on:
    - redis
    - mongodb
    - influxdb
    links:
    - redis:redis
    - mongodb:mongodb
    - influxdb:influxdb
    ports:
    - "8080/tcp"
    volumes:
    - ./application-ws.conf:/override.conf:ro
    command: ["run", "-Dconfig.file=/override.conf"]
