version: '3.7'
services:
  nginx:
    build:
      context: ./
      dockerfile: Dockerfile.nginx
    image: lichess/nginx:1.0
    depends_on:
    - lichess
    - lichess-ws
    ports:
    - "80:80/tcp"
    - "443:443/tcp"

  redis:
    image: redis:4

  mongodb:
    image: mongo:3.2

  influxdb:
    image: influxdb:1.7
    volumes:
    - "./influxdb/init.iql:/docker-entrypoint-initdb.d/init.iql:ro"

  lichess:
    build: ./
    image: lichess:1de207
    stdin_open: true
    tty: true
    depends_on:
    - redis
    - mongodb
    links:
    - redis:redis
    - mongodb:mongodb
    volumes:
    - ./application.conf:/home/lichess/projects/lila/conf/application.conf:ro
    - ./GeoLite2-City.mmdb:/home/lichess/projects/lila/data/GeoLite2-City.mmdb:ro

  lichess-ws:
    build:
      context: ./
      dockerfile: Dockerfile.lichess-ws
    image: lichess/ws:20b2d86
    stdin_open: true
    tty: true
    depends_on:
    - redis
    - mongodb
    - influxdb
    links:
    - redis:redis
    - mongodb:mongodb
    - influxdb:influxdb
    ports:
    - "8080/tcp"
    volumes:
    - ./application-ws.conf:/application.conf:ro
    command: ["run", "-Dconfig.file=/application.conf"]
