FROM nginx:1.17
COPY --from=lichess/nginx-node-stage:1.0 /home/lichess/projects/lila/public /home/lichess/projects/lila/public
# grab curl too
COPY --from=lichess/nginx-node-stage:1.0 /usr/bin/curl /usr/bin/curl
COPY --from=lichess/nginx-node-stage:1.0 /usr/lib /usr/lib
COPY --from=lichess/nginx-node-stage:1.0 /lib /usr/lib
#
COPY nginx.conf /etc/nginx/nginx.conf
